[package]
name         = "api-bin"
version      = "0.1.0"
edition      = "2021"
license-file = "../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api            = { path = "../api" }
domain         = { path = "../domain" }
application    = { path = "../application" }
infrastructure = { path = "../infrastructure" }

sqlx               = { version = "0.5", features = ["runtime-tokio-rustls", "postgres"] }
anyhow             = "1"
axum               = { version = "0.5.1", features = ["tower-log"] }
tokio              = { version = "1.17.0", features = ["full"] }
clap               = "3"
dotenv             = "0.15.0"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http         = { version = "0.3.0", features = ["trace"] }
